#! /bin/sh

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"




## BSPWM config
###############

bspc config border_radius                 0
bspc config border_width                  1
bspc config window_gap                    10
bspc config -m LVDS1 top_padding          20
bspc config -m VGA1 top_padding           0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner




## BSPWM coloring
#################

bspc config normal_border_color   "#4d4f68"
bspc config active_border_color   "#1e1f29"
bspc config focused_border_color  "#ff9500"
bspc config presel_feedback_color "#ff9500"
bspc config urgent_border_color   "#ff6e6e"




## KEYLAYOUT
###########

setxkbmap -layout it  # gb,it,us
xmodmap ~/.Xmodmap

# systemctl --user restart touchcursor.service




## MONITORS
###########

if [[ $(xrandr -q | grep 'eDP1 connected') ]]; then
    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
fi

if [[ $(xrandr -q | grep 'HDMI1 connected') ]]; then
    xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output HDMI1 --mode 1280x1024 --rotate normal --left-of eDP1
    bspc monitor HDMI1 -d 1
fi

if [[ $(xrandr -q | grep 'LVDS1 connected') ]]; then
    bspc monitor LVDS1 -d 1 2 3 4 5 6 7 8 9 0
fi

if [[ $(xrandr -q | grep 'VGA1 connected') ]]; then
    xrandr --output LVDS1 --primary --mode 1600x900 --rotate normal --output VGA1 --mode 1280x1024 --rotate normal --left-of LVDS1
    bspc monitor VGA1 -d 1
fi




## WALLPAPER
############

if [ -x "$(command -v feh)" ]; then
    FILE=/etc/resolv.conf
    if [ -f ~/.fehbg ]; then
        ~/.fehbg
    else
        feh --bg-fill --no-fehbg $SCRIPTPATH/background.jpg
    fi
fi




## NETWORK, BLUETOOTH, KEYS
###########################

nm-applet &
blueman-applet &
sxhkd &




## PICOM
########

if [ -x "$(command -v picom)" ]; then
    picom --daemon --experimental-backends &
fi




## POLYBAR
##########

if [ -x "$(command -v polybar)" ]; then
    killall -q polybar
    while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
    polybar -c $SCRIPTPATH/polybar.ini master &

    # if [[ $(xrandr -q | grep 'VGA1 connected') ]]; then
    #     polybar -c $SCRIPTPATH/polybar.ini slave &
    # fi
fi
