#!/usr/bin/env bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
MONITOR=1 && [[ $(xrandr --query | grep " connected" | cut -d" " -f1 | wc -l) -eq 1 ]] && MONITOR=0




## BSPWM config
###############

bspc config border_radius                 0
bspc config border_width                  1
bspc config window_gap                    10
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner




## BSPWM coloring
#################

bspc config normal_border_color   "#4d4f68"
bspc config active_border_color   "#1e1f29"
bspc config focused_border_color  "#ff9500"
bspc config presel_feedback_color "#ff9500"
bspc config urgent_border_color   "#ff6e6e"




## SPECIFIC LAYOUTS
###################

bspc rule -a Zathura state=tiled




## KEYLAYOUT
############

setxkbmap -layout it  # gb,it,us
xmodmap ~/.Xmodmap




## SXHKD, MONITORS, POLYBAR, WALLPAPER, PICOM, SYSICONS
#######################################################

$SCRIPTPATH/bspwm-sxhkd
$SCRIPTPATH/bspwm-polybar $($SCRIPTPATH/bspwm-monitor)
$SCRIPTPATH/bspwm-picom $MONITOR
$SCRIPTPATH/bspwm-wallpaper
$SCRIPTPATH/bspwm-sysicons
