#!/usr/bin/env bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

MASTERMON=$(xrandr --query | grep " connected" | awk 'NR==1 {print $1}')
MASTERRAT=$(xrandr --query | grep " connected" | awk 'NR==1 {print $4}')

if [[ $(xrandr --query | grep " connected" | cut -d" " -f1 | wc -l) -eq 2 ]]; then
    SLAVEMON=$(xrandr --query | grep " connected" | awk 'NR==2 {print $1}')
    SLAVERAT=$(xrandr --query | grep " connected" | awk 'NR==2 {print $3}')
    xrandr --output $MASTERMON --primary --mode ${MASTERRAT%%+*} --rotate normal --output $SLAVEMON --mode ${SLAVERAT%%+*} --rotate normal --left-of $MASTERMON
    bspc monitor $MASTERMON -d 1
    bspc monitor $SLAVEMON -d 1 2 3 4 5 6 7 8 9 0
    echo $SLAVEMON
else
    xrandr --output $MASTERMON --primary --mode ${MASTERRAT%%+*} --rotate normal
    bspc monitor $MASTERMON -d 1 2 3 4 5 6 7 8 9 0
    echo $MASTERMON
fi
