#! /bin/sh

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"




## AUTOSTART
############

# picom
if [ -x "$(command -v picom)" ]; then
    picom --daemon --experimental-backends &> /dev/null
fi

# wallpaper
if [ -x "$(command -v feh)" ]; then
    FILE=/etc/resolv.conf
    if [ -f ~/.fehbg ]; then
        ~/.fehbg
    else
        feh --bg-fill --no-fehbg $SCRIPTPATH/background.jpg
    fi
fi

# polybar
monitors="$(polybar -m | wc -l)"
for i in `seq 1 $monitors`;
do
    echo $i
    monitor="$(polybar -m | sed -n ${i}p | sed s/:.*// | tac)"
    echo $monitor 
    monitor=$monitor polybar -c $SCRIPTPATH/polybar.ini mainbar &> /dev/null &
done

# network, bluetooth, keys
nm-applet &
blueman-applet &
sxhkd &

# keylayout
setxkbmap -layout gb
xmodmap ~/.Xmodmap




## MONITORS
###########

# (xrandr --listactivemonitors)
bspc monitor LVDS1 -d 1 2 3 4 5 6 7 8 9




## BSPWM config
###############

bspc config border_radius                 0
bspc config border_width                  1
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner




## BSPWM coloring
#################

bspc config normal_border_color		      "#4d4f68"
bspc config active_border_color	          "#1e1f29"
bspc config focused_border_color	      "#ff9500"
bspc config presel_feedback_color	      "#ff9500"
bspc config urgent_border_color 	      "#ff6e6e"




## POLYBAR hidden when fullscreen for vlc, youtube, mpv
#######################################################

# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)




## BSPC rule
############

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
