#! /usr/bin/env bash

# # The key combo argument has the following form: "[C-][M-][S-]KEY",
# # where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# # keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

# rotate() {
# 	degree="$1"
# 	tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
# 		case "$(file -b -i "$file")" in
# 		image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
# 		*)           mogrify  -rotate "$degree" "$file" ;;
# 		esac
# 	done
# }

while read file
do
    case "$1" in
        "C-d")
                rm -i "$file" ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        "C-f")
                feh --bg-fill "$file" ;;
    esac
done

