#! /usr/bin/env bash

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X,
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.
# Instead of moving currebt file to ~/.trash, you could `rm -i "$file" ;;`

if [ ! -d "~/.trash" ]; then
    mkdir ~/.trash
fi

while read file
do
    case "$1" in
        "C-d")
                mv "$file" ~/.trash ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-b")
                feh --bg-fill "$file" ;;
    esac
done

