#!/bin/bash


## SCRIPTPATH
#############

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


## Set background
#################

if [ -x "$(command -v feh)" ]; then
    feh --bg-scale $SCRIPTPATH/down.jpg
fi


## Unload the theme
###################

echo "UnloadTheme" > $XDG_RUNTIME_DIR/leftwm/commands.pipe


## Kill some motherfucker
#########################

pkill picom
pkill polybar
